spring:
  datasource:
    url: jdbc:mysql://mysql:3306/app_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: app_user
    password: app_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: none
