version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hanghae_cinema
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql:ro
    command: --lower_case_table_names=1

volumes:
  db_data: